spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/dealership_test
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false